apiVersion: v2
type: application
name: odoo-test
description: odoo-test
version: 1.0.0
appVersion: 0.0.1
maintainers:
  - name: Peter Benicky
    email: peter@benicky.info
    url: https://benicky.info