apiVersion: v1
kind: PersistentVolume # Create a PV
metadata:
  # Valumes are in k8, som name must be unique, namespace is not relevant here
  # it is  cluster-scoped resource
  name: postgresql-data-{{ .Values.namespace }}
  # namespace: {{ .Values.namespace }}
  labels:
    type: local # Sets PV's type to local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/{{ .Values.namespace }}/volume" # Sets the volume's path
